import type { Listing } from "@/types";

export const listings: Listing[] = [
  {
    id: "1",
    title: "Modern Downtown Loft",
    description: "A beautiful and spacious loft in the heart of the city. Fully furnished with modern amenities. Perfect for young professionals.",
    price: 2500,
    location: {
      address: "123 Main St, Apt 4B",
      city: "Metropolis",
      country: "USA",
      lat: 40.7128,
      lng: -74.0060,
    },
    images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    beds: 2,
    baths: 2,
    amenities: ["Wifi", "Kitchen", "Washer", "Dryer", "Air Conditioning", "Heating", "Elevator"],
    verified: true,
    type: "Flat",
  },
  {
    id: "2",
    title: "Cozy Suburban House",
    description: "Charming house with a backyard garden. Located in a quiet, family-friendly neighborhood. Close to parks and schools.",
    price: 3200,
    location: {
      address: "456 Oak Ave",
      city: "Suburbia",
      country: "USA",
      lat: 40.7528,
      lng: -73.9860,
    },
    images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    beds: 3,
    baths: 2.5,
    amenities: ["Wifi", "Kitchen", "Parking", "Garden", "Pet Friendly", "Heating"],
    verified: true,
    type: "House",
  },
  {
    id: "3",
    title: "Sunny Room with a View",
    description: "A private room in a shared apartment with stunning city views. Access to all shared spaces including kitchen and living room.",
    price: 1200,
    location: {
      address: "789 High Street, Room 3",
      city: "Metropolis",
      country: "USA",
      lat: 40.7328,
      lng: -74.0160,
    },
    images: ["https://placehold.co/600x400.png"],
    beds: 1,
    baths: 1,
    amenities: ["Wifi", "Kitchen", "Elevator", "Air Conditioning"],
    verified: false,
    type: "Room",
  },
  {
    id: "4",
    title: "Luxury Penthouse Suite",
    description: "Experience luxury living in this exclusive penthouse. Breathtaking views, rooftop pool, and 24/7 concierge service.",
    price: 7500,
    location: {
      address: "101 Sky Tower",
      city: "Metropolis",
      country: "USA",
      lat: 40.7228,
      lng: -73.9960,
    },
    images: ["https://placehold.co/600x400.png", "https://placehold.co/600x400.png", "https://placehold.co/600x400.png"],
    beds: 4,
    baths: 4,
    amenities: ["Wifi", "Pool", "Gym", "Parking", "Concierge", "Air Conditioning", "Elevator"],
    verified: true,
    type: "Flat",
  },
  {
    id: "5",
    title: "Quaint Countryside Cottage",
    description: "Escape the city to this peaceful cottage. Surrounded by nature, it's the perfect retreat for artists and writers.",
    price: 1800,
    location: {
      address: "22 Country Lane",
      city: "Green Valley",
      country: "USA",
      lat: 40.8128,
      lng: -74.0560,
    },
    images: ["https://placehold.co/600x400.png"],
    beds: 2,
    baths: 1,
    amenities: ["Kitchen", "Fireplace", "Garden", "Parking", "Pet Friendly"],
    verified: true,
    type: "House",
  },
  {
    id: "6",
    title: "Affordable Student Room",
    description: "A simple and clean room near the university campus. Ideal for students looking for a quiet place to study and rest.",
    price: 800,
    location: {
      address: "33 University Rd",
      city: "College Town",
      country: "USA",
      lat: 40.6928,
      lng: -74.0260,
    },
    images: ["https://placehold.co/600x400.png"],
    beds: 1,
    baths: 1,
    amenities: ["Wifi", "Desk", "Heating"],
    verified: true,
    type: "Room",
  },
];
